bank/api/urls.py
from bank.api.views import TransactionViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('', TransactionViewSet, basename='articles')
urlpatterns = router.urls

bank/urls.py
from django.urls import path, re_path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'bank'
urlpatterns = [
    path('', views.profile, name="profile"),
    path('users/', views.userlist, name="users"),
    path('update-profile/', views.update_profile, name="update_profile"),
    path('transactions/<int:pk>/', views.trasactionList, name="transactions"),
    path('<int:user_id>/create-trans/',
         views.AddTransaction.as_view(), name="create_trans"),
    path('delete/<int:trans_id>/', views.delete_transaction, name="delete_trans"),
    path('login/', auth_views.LoginView.as_view(template_name="bank/login.html"), name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_request, name="logout"),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='bank/users/password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='bank/users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='bank/users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='bank/users/password_reset_complete.html'),
         name='password_reset_complete'),

    # For OTP
    re_path(r'^totp/create/$', views.TOTPCreateView.as_view(), name='totp-create'),
    re_path(r'^totp/login/(?P<token>[0-9]{6})/$',
            views.TOTPVerifyView.as_view(), name='totp-login'),
]

bankSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    # path('phone_login/', include('phone_login.urls'),),
    path('', include('bank.urls')),
    path('api/', include('bank.api.urls')),
]

bank/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

import random


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_no = models.CharField(max_length=12, blank=False)
    account_number = models.IntegerField(
        verbose_name="Account number", default=random.randint(100, 1000))
    account_balance = models.IntegerField(default=100)
    date_joined = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username

    def __getattr__(self, name):
        return getattr(self.original, name)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()


class Transaction(models.Model):
    types = [
        ('Deposit', "DEPOSIT"),
        ('Withdraw', "WITHDRAW")
    ]

    account = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    description = models.CharField(max_length=20, default="N/A")
    trans_date = models.DateTimeField(default=timezone.now)
    trans_type = models.CharField(
        verbose_name="Transaction Type", max_length=20, choices=types, default="Deposit")

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse("bank:profile")

    def save(self, *args, **kwargs):
        if self.trans_type == 'Withdraw':
            self.account.profile.account_balance -= self.amount
        else:
            self.account.profile.account_balance += self.amount
        self.account.save()
        # Call the real save() method
        super(Transaction, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.account.profile.account_balance -= self.amount
        self.account.save()
        super(Transaction, self).delete(*args, **kwargs)

bank/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Transaction


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email",
                  "username", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class EditProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class AddTransaction(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ("amount", "description", "trans_type")

bank/api/views.py
from rest_framework import viewsets

from bank.models import Transaction
from .serializers import TransactionSerializer


class TransactionViewSet(viewsets.ModelViewSet):
    serializer_class = TransactionSerializer
    queryset = Transaction.objects.all()

bank/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin

from .models import Profile, Transaction
from .forms import NewUserForm, EditProfile, AddTransaction

# For OTP
from rest_framework import views, permissions
from rest_framework.response import Response
from rest_framework import status
from django_otp import devices_for_user
from django_otp.plugins.otp_totp.models import TOTPDevice


# Display all users
@login_required
def userlist(request):
    user_list = User.objects.all().order_by('first_name')
    return render(request, "bank/users.html", {"users": user_list})


# Details of logged in user
@login_required
def profile(request):
    return render(request, "bank/profile.html")


# Update profile
@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = EditProfile(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(
                request, "Your changes have been updated successfully !")
            return redirect("bank:profile")
        else:
            messages.info(request, "Please correct the errors below.")
    else:
        user_form = EditProfile(instance=request.user)

    return render(request, "bank/update_profile.html", {"form": user_form})


# Displays the transactions of the logged in account
@login_required
def trasactionList(request, pk):
    trans = Transaction.objects.filter(account=pk)
    main_user = User.objects.get(id=pk)
    return render(request, "bank/transactions.html", {"transactions": trans, "main_user": main_user})


# Add Transaction
class AddTransaction(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Transaction
    fields = ['amount', 'description', 'trans_type']
    template_name = "bank/create_trans.html"
    success_message = "Transaction made successfully"

    def form_valid(self, form):
        form.instance.account = self.request.user
        return super().form_valid(form)


# Delete a transaction
@login_required
def delete_transaction(request, trans_id):
    trans = Transaction.objects.get(pk=trans_id)
    trans.delete()
    return redirect("bank:transactions", request.user.id)


# Register user
def register(request):
    if request.method == 'POST':
        form = NewUserForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('first_name')
            messages.success(request, f"New account created: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            messages.success(
                request, f"Rs. 100 have been credited to your account as bonus : )")
            return redirect("bank:profile")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = NewUserForm
    return render(request,
                  "bank/register.html",
                  context={"form": form})


# Logout user
@login_required
def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully !!")
    return redirect("bank:login")


# For OTP
# def get_user_totp_device(self, user, confirmed=None):
#     devices = devices_for_user(user, confirmed=confirmed)
#     for device in devices:
#         if isinstance(device, TOTPDevice):
#             return deviceclass TOTPCreateView(views.APIView):
#     """
#     Use this endpoint to set up a new TOTP device
#     """
#     permission_classes = [permissions.IsAuthenticated] def get(self, request, format=None):
#         user = request.user
#         device = get_user_totp_device(self, user)
#         if not device:
#             device = user.totpdevice_set.create(confirmed=False)
#         url = device.config_url
#         return Response(url, status=status.HTTP_201_CREATED)class TOTPVerifyView(views.APIView):
#     """
#     Use this endpoint to verify/enable a TOTP device
#     """
#     permission_classes = [permissions.IsAuthenticated] def post(self, request, token, format=None):
#         user = request.user
#         device = get_user_totp_device(self, user)
#         if not device == None and device.verify_token(token):
#             if not device.confirmed:
#                 device.confirmed = True
#                 device.save()
#             return Response(True, status=status.HTTP_200_OK)
#         return Response(status=status.HTTP_400_BAD_REQUEST)

bank/templates/bank/create_trans.html
{% extends 'bank/home.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Create Transaction</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-primary" type="submit">Add</button>
                </div>
            </form>
    </div>

{% endblock content %}

bank/templates/bank/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank System</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
             integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="{% static 'bank/main.css' %}" type="text/css">
</head>
<body>
    
    {% include "bank/includes/navbar.html" %}

    {% include "bank/includes/messages.html" %}

    <div class="container">
        <br/>
        {% block content %}
        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
                integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" 
                integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#trans-table').DataTable();
        });
    </script>
</body>
</html>

bank/templates/bank/login.html
{% extends 'bank/home.html' %} 
{% load crispy_forms_tags %}
{% block content %}

   <div class="content">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted">
                    <a class="ml-3" href="{% url 'bank:password_reset' %}">
                        <strong>Forgot Password?</strong>
                    </a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Don't have an account? <a class="ml-1" href="{% url 'bank:register' %}"><strong>Register</strong></a></small>
        </div>
   </div>

{% endblock content %}

bank/templates/bank/profile.html
{% extends 'bank/home.html' %}
{% block content %}
    <div class="container">
        <h1>Account Details</h1><br><br>
        <div class="profile" style="font-size: 25px;">
            <table class="table table-dark table-responsive-sm">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>{{user.first_name}} {{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Account Number</td>
                        <td>xxxxxxxxxx{{user.profile.account_number}}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td>Date Joined</td>
                        <td>{{ user.date_joined|date:"F j, Y" }}</td>
                    </tr>
                    <tr>
                        <td>Balance</td>
                        <td>Rs. {{ user.profile.account_balance }}</td>
                    </tr>
                </tbody>
            </table>
            <br><br>
        </div>
        {% if user.is_active %}
            <button class="btn btn-primary mt-3 mr-3" >
                <a href="{% url "bank:update_profile" %}" style="text-decoration: none; color: #000;">Update Profile</a>
            </button>
        {% endif %}

        <button class="btn btn-warning mt-3 mr-3" >
            <a href="{% url "bank:transactions" user.id %}" style="text-decoration: none; color: #000;">Go to banking</a>
        </button>

        <button class="btn btn-success mt-3" >
            <a href="/api" style="text-decoration: none; color: #000;">Visit and use our API endpoints</a>
        </button>
    </div>
{% endblock content %}

bank/templates/bank/register.html
{% extends 'bank/home.html' %} 
{% load crispy_forms_tags %}
{% block content %}

   <div class="container">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">Already have an account? <a class="ml-1" href="{% url 'bank:login' %}"><strong>Login</strong></a></small>
        </div>
   </div>

{% endblock content %}

bank/templates/bank/transactions.html
{% extends 'bank/home.html' %}
{% block content %}

    <div class="container">
        {% if user.id == main_user.id %}
            <div class="text-center">
                <a href="{% url "bank:create_trans" user.id %}">
                    <button class="btn btn-outline-primary p-2">
                        <strong>Create Transaction</strong>
                    </button>
                </a>
            </div>
        {% endif %}
        <br><br>
        <table class="table table-responsive-sm" id="trans-table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Transaction ID</th>
                    <th scope="col">Description</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Date</th>
                    <th scope="col">Type</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for trans in transactions %}
                    <tr>
                        <td>{{trans.id}}</td>
                        <td>{{trans.description}}</td>
                        <td>{{trans.amount}}</td>
                        <td>{{trans.trans_date}}</td>
                        <td>{{trans.trans_type}}</td>
                        <td>
                            <a href="{% url 'bank:delete_trans' trans.id %}">
                                <button class="btn btn-sm btn-danger">Delete</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
    </div>

{% endblock content %}

bank/templates/bank/update_profile.html
{% extends 'bank/home.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Update</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-primary" type="submit">Save Changes</button>
                </div>
            </form>
    </div>

{% endblock content %}

bank/templates/bank/users.html
{% extends 'bank/home.html' %}
{% block content %}

    <div class="container">
        <br><br>
        <table class="table table-responsive-sm" id="trans-table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">User ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Balance</th>
                    <th scope="col">Account Number</th>
                    <th scope="col">Date joined</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.first_name}} {{user.last_name}}</td>
                        <td>{{user.profile.account_balance}}</td>
                        <td>{{user.profile.account_number}}</td>
                        <td>{{user.date_joined}}</td>
                        <td>
                            <a href="{% url 'bank:transactions' user.id %}">
                                <button class="btn btn-sm btn-outline-info">View Transactions</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
    </div>

{% endblock content %}